import React, { useEffect, useState } from 'react';
import { Bot, FileUp, History, Users, ScanSearch, Palette, Download, BarChart3, Send, Play, CheckCircle2, Loader2 } from 'lucide-react';
import { apiRequest, getAuthToken } from '../services/api';
import './CompetitionSuite.css';

const features = [
  [Bot,'Real AI Editor','Gemini-powered rewriting with a safe local fallback'],[FileUp,'Smart Import','PDF, DOCX, TXT and Markdown to editable chapters'],[History,'Version History','Create snapshots and safely restore manuscripts'],[Users,'Collaboration','Invite teammates and collect manuscript comments'],[ScanSearch,'Originality Scan','Internal repetition and citation-quality checks'],[Palette,'Cover Concepts','AI art direction with a ready-to-use palette'],[Download,'Pro Export','Download PDF, DOCX and EPUB editions'],[BarChart3,'Author Analytics','Views, downloads, completions and conversion'],[Send,'Publisher Tracker','Prepare and track manuscript submissions'],[Play,'Judge Demo Mode','A guided end-to-end competition story']
];

export default function CompetitionSuite({ user, openAuthModal, setActivePage, setSelectedBookId }) {
  const [books,setBooks]=useState([]); const [bookId,setBookId]=useState(''); const [running,setRunning]=useState(false); const [step,setStep]=useState(0); const [message,setMessage]=useState('');
  useEffect(()=>{ if(user) apiRequest('/books/').then(data=>{setBooks(data);setBookId(data[0]?.id||'');}).catch(()=>{}); },[user]);
  const runDemo=()=>{setRunning(true);setStep(0);setMessage(''); let current=0; const timer=setInterval(()=>{current+=1;setStep(current);if(current===5){clearInterval(timer);setRunning(false);setMessage('Demo complete — manuscript imported, improved, reviewed and prepared for publishing.');}},650);};
  const importFile=async(event)=>{const file=event.target.files?.[0];if(!file)return; if(!user){openAuthModal('signup');return;} setMessage('Importing manuscript…'); const body=new FormData();body.append('file',file);try{const result=await apiRequest('/manuscripts/import','POST',body,true);setSelectedBookId(result.id);setMessage(`Imported “${result.title}” into ${result.chapters.length} editable chapter(s).`);setActivePage('studio');}catch(error){setMessage(error.message);}};
  const exportBook=(format)=>{if(!bookId){setMessage('Create or import a book first.');return;}const token=getAuthToken();fetch(`/api/v1/export/${format}/${bookId}`,{headers:{Authorization:`Bearer ${token}`}}).then(async response=>{if(!response.ok)throw new Error('Export failed');const blob=await response.blob();const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`panna-book.${format}`;a.click();URL.revokeObjectURL(url);setMessage(`${format.toUpperCase()} export downloaded.`);}).catch(error=>setMessage(error.message));};
  return <div className="suite-page">
    <header className="suite-hero"><div><span className="suite-kicker">PANNA.AI COMPETITION SUITE</span><h1>One idea. Ten production-ready capabilities.</h1><p>Show judges a complete author journey—from importing a rough manuscript to AI review, collaboration, professional export and publisher outreach.</p><div className="suite-actions"><button onClick={runDemo} disabled={running}>{running?<Loader2 className="spin-icon" size={18}/>:<Play size={18}/>} Run 2-minute demo</button><label><FileUp size={18}/> Import manuscript<input type="file" accept=".pdf,.docx,.txt,.md" onChange={importFile}/></label></div></div><div className="demo-panel"><strong>LIVE DEMO PIPELINE</strong>{['Import manuscript','Structure chapters','AI editorial review','Human approval','Export & submit'].map((item,index)=><div className={step>index?'done':step===index&&running?'active':''} key={item}><span>{step>index?<CheckCircle2 size={17}/>:index+1}</span>{item}</div>)}</div></header>
    {message&&<div className="suite-message">{message}</div>}
    <section className="feature-grid">{features.map(([Icon,title,desc],index)=><article key={title}><div className="feature-number">{String(index+1).padStart(2,'0')}</div><Icon size={22}/><h3>{title}</h3><p>{desc}</p></article>)}</section>
    <section className="export-bar"><div><h2>Publish-ready exports</h2><p>Select one of your manuscripts and generate a professional edition.</p></div>{user?<select value={bookId} onChange={e=>setBookId(e.target.value)}><option value="">Select manuscript</option>{books.map(book=><option value={book.id} key={book.id}>{book.title}</option>)}</select>:<button onClick={()=>openAuthModal('signup')}>Create author account</button>}<div className="export-buttons">{['pdf','docx','epub'].map(format=><button key={format} onClick={()=>exportBook(format)}>{format.toUpperCase()}</button>)}</div></section>
  </div>;
}
